FROM python:3.14-alpine3.22 AS build
WORKDIR /opt/server
COPY *.py .
COPY payment.ini .
COPY requirements.txt .
RUN apk add --no-cache gcc python3-dev musl-dev linux-headers
RUN pip3 install -r requirements.txt


FROM python:3.14-alpine3.22
WORKDIR /opt/server
COPY --from=build /opt/server /opt/server
COPY --from=build /usr/local/ /usr/local/
ENV CART_HOST=cart \
    CART_PORT=8080 \
    USER_HOST=user \
    USER_PORT=8080 \
    AMQP_HOST=rabbitmq \ 
    AMQP_USER=roboshop \ 
    AMQP_PASS=roboshop123 
RUN addgroup -S -g 1001 roboshop && adduser -S -u 1001 roboshop -G roboshop
RUN chown -R roboshop:roboshop /opt/server
USER roboshop
CMD [ "uwsgi", "--ini", "payment.ini" ]