FROM node:20.20.2-alpine3.22 AS build
WORKDIR /opt/server
COPY *.js .
COPY *.json .
RUN npm install

FROM node:20.20.2-alpine3.22
WORKDIR /opt/server
COPY --from=build /opt/server /opt/server
EXPOSE 8080
ENV REDIS_HOST=redis \
    CATALOGUE_HOST=catalogue \
    CATALOGUE_PORT=8080
RUN addgroup -S roboshop && adduser -S roboshop -G roboshop && \
    chown -R roboshop:roboshop /opt/server
USER roboshop
CMD ["server.js"]
ENTRYPOINT [ "node" ]
