FROM maven:3.5-alpine AS build
WORKDIR /opt/server
COPY pom.xml .
COPY src ./src
RUN mvn clean package
RUN mv target/shipping-1.0.jar shipping.jar 



FROM eclipse-temurin:11-jre-alpine
EXPOSE 8080
WORKDIR /opt/server
RUN addgroup -S roboshop && adduser -S roboshop -G roboshop
COPY --chown=roboshop:roboshop --from=build /opt/server/shipping.jar .
ENV CART_ENDPOINT=cart:8080 \
    DB_HOST=mysql
USER roboshop
CMD ["-jar", "shipping.jar"]
ENTRYPOINT [ "java" ]
