FROM node:20.20.2-alpine3.22 AS build
WORKDIR /opt/server
COPY *.js .
COPY *.json .
RUN npm install

FROM node:20.20.2-alpine3.22
COPY --from=build /opt/server /opt/server
EXPOSE 8080
ENV MONGO=true \
    REDIS_URL='redis://redis:6379' \
    MONGO_URL="mongodb://mongodb:27017/users"
RUN addgroup -S roboshop && adduser -S roboshop -G roboshop
RUN chown -R roboshop:roboshop /opt/server
USER roboshop
CMD ["server.js"]
ENTRYPOINT [ "node" ]
